# Generated by Django 4.2.14 on 2024-09-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customers_product_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
