# Generated by Django 4.2.14 on 2024-09-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_developer_projectmanager_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='developers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='user.developer'),
        ),
    ]
